spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdetails?useSSL=false
    username: root
    password: Itsmejana_17

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: create
